### ISSUE TITLE
ERROR: Invalid salt version: 2

### ISSUE THREAD

**Issue by bokeyy** [dcodeIO/bcrypt.js#20]
Error: Invalid salt version: 2
    at Error (<anonymous>)
    at _hash (/var/www/bokeyy_ghost/node_modules/bcryptjs/dist/bcrypt.js:1083:19)
    at Object.bcrypt.hash (/var/www/bokeyy_ghost/node_modules/bcryptjs/dist/bcrypt.js:172:13)
    at bcrypt.compare (/var/www/bokeyy_ghost/node_modules/bcryptjs/dist/bcrypt.js:218:16)
    at ret (eval at makeNodePromisifiedEval (/var/www/bokeyy_ghost/node_modules/bluebird/js/main/promisify.js:201:12), <anonymous>:15:26)
    at /var/www/bokeyy_ghost/core/server/models/user.js:667:24
    at tryCatch1 (/var/www/bokeyy_ghost/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/var/www/bokeyy_ghost/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/var/www/bokeyy_ghost/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/var/www/bokeyy_ghost/node_modules/bluebird/js/main/promise.js:713:18)

POST /ghost/api/v0.1/authentication/token 500 17.652 ms - 79

**Comment by dcodeIO** [comment]
This looks like a malformed hash to me, containing a salt beginning with "2" instead of "$2".
