### ISSUE TITLE
Error: Invalid salt version: nu

### ISSUE THREAD

**Issue by julianlam** [dcodeIO/bcrypt.js#6]
Experienced on production server.

``` plaintext
Error: Invalid salt version: nu
    at Error (<anonymous>)
    at w (/path/to/app/node_modules/bcryptjs/bcrypt.min.js:11:43)
    at Object.m.hash (/path/to/app/node_modules/bcryptjs/bcrypt.min.js:39:173)
    at Object.m.compare (/path/to/app/node_modules/bcryptjs/bcrypt.min.js:40:133)
    at /path/to/app/src/routes/authentication.js:201:13
    at /path/to/app/src/database/redis/hash.js:43:4
    at /path/to/app/src/database/redis/hash.js:69:4
    at /path/to/app/node_modules/redis/index.js:1077:13
    at try_callback (/path/to/app/node_modules/redis/index.js:532:9)
    at RedisClient.return_reply (/path/to/app/node_modules/redis/index.js:614:13)
```

**Comment by bokeyy** [comment]
https://github.com/felixrieseberg/Ghost-Azure/issues/1

It happens again.

**Comment by ericjun0203** [comment]
There is some problems in bCrypt
